[package]
name = "espacial-infrastructure"
description = "Infrastructure adapters for Espacial server use cases"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
espacial-application = { path = "../espacial-application" }

[lints]
workspace = true
